### ISSUE TITLE
Please consider renaming public to public_dir as it hides the public method in Module

### ISSUE THREAD

**Issue by krisselden** [bmizerany/sinatra#4]
I'm trying to decorate the error method as follows:

alias_method_chain :error, :formatting

but this is failing here:

def alias_method_chain(target, feature)
  ...
  case
      when public_method_defined?(without_method)

> >    public target
> >   ...
> > end

because of:

set :public, Proc.new { root && File.join(root, 'public') }

**Comment by kyledrake** [comment]
This is not the active Sinatra repository, it is here now: http://github.com/sinatra/sinatra
